name: newmanReport

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Create dir
        run: mkdir testArtifacts

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.3
        with:
          node-version: '16.x'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra

      - name: Run Tests 
        run: newman run ".github/workflows/PostmanPokemonConsulta.postman_collection.json" -d ".github/workflows/test_case_pokemon.json" -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html

      - name: Output the results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: testArtifacts
